//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideSharingWPApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RideSharingWPApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my application.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic informatiion:.
        /// </summary>
        public static string basicInfo {
            get {
                return ResourceManager.GetString("basicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept .
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added .
        /// </summary>
        public static string btnAddVehicle {
            get {
                return ResourceManager.GetString("btnAddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string btnChangePass {
            get {
                return ResourceManager.GetString("btnChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaceBook: facebook.com/ridesharing.
        /// </summary>
        public static string contact1 {
            get {
                return ResourceManager.GetString("contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail:ridesharing@gmail.com.
        /// </summary>
        public static string contact2 {
            get {
                return ResourceManager.GetString("contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Plus:googleplus.com/ridesharing.
        /// </summary>
        public static string contact3 {
            get {
                return ResourceManager.GetString("contact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube:youtube.com/ridesharing.
        /// </summary>
        public static string contact4 {
            get {
                return ResourceManager.GetString("contact4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample assumes that people above 18 years of age are eligible to vote..
        /// </summary>
        public static string displayMessage {
            get {
                return ResourceManager.GetString("displayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s Information.
        /// </summary>
        public static string driverInformation {
            get {
                return ResourceManager.GetString("driverInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s License.
        /// </summary>
        public static string driverLicense {
            get {
                return ResourceManager.GetString("driverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Lincense&apos;s photo.
        /// </summary>
        public static string driverLincensePhoto {
            get {
                return ResourceManager.GetString("driverLincensePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks .
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string headerAccepted {
            get {
                return ResourceManager.GetString("headerAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string headerCreated {
            get {
                return ResourceManager.GetString("headerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string headerCustomer {
            get {
                return ResourceManager.GetString("headerCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string headerFinished {
            get {
                return ResourceManager.GetString("headerFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string headerInfor {
            get {
                return ResourceManager.GetString("headerInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List intinerary.
        /// </summary>
        public static string headerList {
            get {
                return ResourceManager.GetString("headerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string headerMap {
            get {
                return ResourceManager.GetString("headerMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting day.
        /// </summary>
        public static string headerStartingDay {
            get {
                return ResourceManager.GetString("headerStartingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting time.
        /// </summary>
        public static string headerStartingTime {
            get {
                return ResourceManager.GetString("headerStartingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string headerVehicle {
            get {
                return ResourceManager.GetString("headerVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost....
        /// </summary>
        public static string hintCost {
            get {
                return ResourceManager.GetString("hintCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure point....
        /// </summary>
        public static string hintDeparture {
            get {
                return ResourceManager.GetString("hintDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinerary description....
        /// </summary>
        public static string hintDescription {
            get {
                return ResourceManager.GetString("hintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination point.....
        /// </summary>
        public static string hintDestination {
            get {
                return ResourceManager.GetString("hintDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance....
        /// </summary>
        public static string hintDistance {
            get {
                return ResourceManager.GetString("hintDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email....
        /// </summary>
        public static string hintInputEmail {
            get {
                return ResourceManager.GetString("hintInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password....
        /// </summary>
        public static string hintInputPass {
            get {
                return ResourceManager.GetString("hintInputPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string hyperlinkForgotPass {
            get {
                return ResourceManager.GetString("hyperlinkForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Ride Sharing team.
        /// </summary>
        public static string infor1 {
            get {
                return ResourceManager.GetString("infor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated in multi-platform : WP, Android and Web.
        /// </summary>
        public static string infor2 {
            get {
                return ResourceManager.GetString("infor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office: 453-455 Hoang Dieu, Danang.
        /// </summary>
        public static string infor3 {
            get {
                return ResourceManager.GetString("infor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile: 0975417597.
        /// </summary>
        public static string infor4 {
            get {
                return ResourceManager.GetString("infor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinerary description:.
        /// </summary>
        public static string itineraryDescription {
            get {
                return ResourceManager.GetString("itineraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate&apos;s photo.
        /// </summary>
        public static string licensePlateImg {
            get {
                return ResourceManager.GetString("licensePlateImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor insurance&apos;s photo.
        /// </summary>
        public static string motorInsuranceImg {
            get {
                return ResourceManager.GetString("motorInsuranceImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have password. Log in now!.
        /// </summary>
        public static string passwordAlready {
            get {
                return ResourceManager.GetString("passwordAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor&apos;s registration certificate.
        /// </summary>
        public static string registrationCertificateImg {
            get {
                return ResourceManager.GetString("registrationCertificateImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending password for this email.
        /// </summary>
        public static string sendPassword {
            get {
                return ResourceManager.GetString("sendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Sharing- Your Happiness moment.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Sharing .
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string tracking {
            get {
                return ResourceManager.GetString("tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string txtComment {
            get {
                return ResourceManager.GetString("txtComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost (VND) :.
        /// </summary>
        public static string txtCost {
            get {
                return ResourceManager.GetString("txtCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure point :.
        /// </summary>
        public static string txtDeparturePoint {
            get {
                return ResourceManager.GetString("txtDeparturePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination point :.
        /// </summary>
        public static string txtDestinationPoint {
            get {
                return ResourceManager.GetString("txtDestinationPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (km) :.
        /// </summary>
        public static string txtDistance {
            get {
                return ResourceManager.GetString("txtDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback:.
        /// </summary>
        public static string txtFeedback {
            get {
                return ResourceManager.GetString("txtFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        public static string txtPersonalID {
            get {
                return ResourceManager.GetString("txtPersonalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor registration&apos;s certificate.
        /// </summary>
        public static string txtRegistrationCertificate {
            get {
                return ResourceManager.GetString("txtRegistrationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting day :.
        /// </summary>
        public static string txtStartingDay {
            get {
                return ResourceManager.GetString("txtStartingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time completed:.
        /// </summary>
        public static string txtTimeCompleted {
            get {
                return ResourceManager.GetString("txtTimeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s photo.
        /// </summary>
        public static string vehicleImg {
            get {
                return ResourceManager.GetString("vehicleImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s information.
        /// </summary>
        public static string vehicleInfor {
            get {
                return ResourceManager.GetString("vehicleInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle plate&apos;s number:.
        /// </summary>
        public static string vehiclePlateNum {
            get {
                return ResourceManager.GetString("vehiclePlateNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle type:.
        /// </summary>
        public static string vehicleType {
            get {
                return ResourceManager.GetString("vehicleType", resourceCulture);
            }
        }
    }
}
